version: '3'
services:
  # pr-helper-ml:
  #   build: domain/ml
  #   # ports:
  #   #   - "5000:5000" # Example port

  pr-helper-server:
    build:
      context: ./domain/server
    ports:
      - "8000:8000" # Example port

  # pr-helper-web:
  #   build:
  #     context: ./domain/web
  #   ports:
  #     - "3000:3000" # Example port
